require('dotenv').config();
const express = require('express');
const morgan = require('morgan');
const cors = require('cors');
const downloadRouter = require('./routes/download');
const searchRouter = require('./routes/search');
const { rateLimiter } = require('./middleware/rateLimiter');
const { errorHandler } = require('./middleware/errorHandler');
const app = express();
app.use(cors());
app.use(express.json());
app.use(morgan('dev'));
app.use(rateLimiter);
app.use('/api/download', downloadRouter);
app.use('/api/search', searchRouter);
app.get('/', (req,res)=>res.json({ok:true,service:'goatbot-ytdl-api'}));
const PORT=process.env.PORT||3000;
app.listen(PORT,()=>console.log(`Server running on http://localhost:${PORT}`));